// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pueoiaivzdbhiygylkok.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB1ZW9pYWl2emRiaGl5Z3lsa29rIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQyNjQzMTUsImV4cCI6MjA1OTg0MDMxNX0.oELevGR-zqGpCGgC1y__c3iMIzLnqjN8xIppbNDcef4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);